### PR TITLE
Make the copyright date dynamic

### PR DESCRIPTION
**Pull request by mattgreenfield**
I've not tested this, you might not even want to do it...

@benjaminparry

### CODE REVIEW

**Comment by benjaminparry** [comment]
Where would you suggest adding the start date if I wanted to include one? In the `_config.yml` file? Something like `copyright-from: 2013`?

**Comment by mattgreenfield** [comment]
I guess hard coding it is fine, it’s not going to change or be used anywhere else is it?

## 

Matt Greenfield
Sent with Airmail

On 10 October 2016 at 19:54:51, Benjamin Parry (notifications@github.commailto:notifications@github.com) wrote:

Where would you suggest adding the start date if I wanted to include one? In the _config.yml file? Something like copyright-from: 2003?

**Comment by benjaminparry** [comment]
Unless I get this blasted time machine working, no.

**Comment by benjaminparry** [comment]
Looking forward to seeing you in your new t-shirt.

Thanks

**Pull request merged**
